name: panseg
channels:
  - conda-forge
dependencies:
  - bioimageio.core==0.9.6
  - bioimageio.spec==0.5.7.4
  - h5py=3.15.1
  - napari=0.6.6
  - pip
  - pydantic==2.12.5
  - pyside6==6.10.2
  - python-elf=0.7.4
  - python-graphviz=0.21
  - python[version='>=3.11']
  - pytorch==2.10.0
  - pyyaml=6.0.3
  - qt-material=2.14
  - qtpy=2.4.3
  - requests=2.32.5
  - scikit-image==0.26.0
  - tensorboard=2.20.0
  - tifffile==2026.3.3
  - vigra=1.12.2
  - zarr=3.1.5
  - trimesh==4.11.3
  - zmesh=1.8.0
  - numpy=2.4
  - pip:
      - -e .
