package:
  name: plantseg
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
  script: "pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  number: 1

  entry_points:
    - plantseg = plantseg.main.plantseg:main

requirements:
  build:
    - python
    - pip

  run:
    - python 3.7
    # TODO: remove pillow dep after new torchvision release
    - pillow<7
    - h5py
    - pywget
    - pyyaml
    - scipy =1.2
    - scikit-image
    - scikit-learn
    - tifffile
    - vigra
    - torchvision
    - pytorch
    - elf
    - gasp
    - pytorch-3dunet

test:
  imports:
    - plantseg
    - plantseg.gui
    - plantseg.segmentation
  requires:
    - pytest
  run:
    - pytest
about:
  home: https://github.com/hci-unihd/plant-seg
  license: MIT