{% set python_min = "3.11" %}
package:
  name: panseg
  version: "2.0.0rc10"

source:
  path: ..

build:
  noarch: python
  number: 1
  script:
    - "pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
    - "mkdir -p {{ PREFIX }}/Menu" # [not win]
    - "cp {{ RECIPE_DIR }}/../Menu/panseg.json {{ PREFIX }}/Menu/{{ PKG_NAME }}_menu.json" # [not win]
    - "cp {{ RECIPE_DIR }}/../Menu/icon.png {{ PREFIX }}/Menu/icon.png" # [not win]
    - "cp {{ RECIPE_DIR }}/../Menu/icon.ico {{ PREFIX }}/Menu/icon.ico" # [not win]
    - "cp {{ RECIPE_DIR }}/../Menu/logo_horizontal.png {{ PREFIX }}/Menu/logo_horizontal.png" # [not win]
    - "cp {{ RECIPE_DIR }}/../Menu/logo_vertical.png {{ PREFIX }}/Menu/logo_vertical.png" # [not win]
    # Only relevant for build, not packaging. In CI and forge, build only runs on linux -> noarch
    # - 'mkdir -p {{ PREFIX }}\Menu' # [win]
    # - 'cp {{ RECIPE_DIR }}\..\Menu\plant-seg.json {{ PREFIX }}\Menu\{{ PKG_NAME }}_menu.json' # [win]
    # - 'cp {{ RECIPE_DIR }}\..\Menu\icon.png {{ PREFIX }}\Menu\icon.png' # [win]
    # - 'cp {{ RECIPE_DIR }}\..\Menu\icon.ico {{ PREFIX }}\Menu\icon.ico' # [win]
    # - 'cp {{ RECIPE_DIR }}\..\Menu\logo_horizontal.png {{ PREFIX }}\Menu\logo_horizontal.png' # [win]
    # - 'cp {{ RECIPE_DIR }}\..\Menu\logo_vertical.png {{ PREFIX }}\Menu\logo_vertical.png' # [win]

  entry_points:
    - panseg = panseg.run_panseg:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools

  run:
    - python >={{ python_min }}
    - pip
    # Neural Network
    - pytorch==2.9.1
    - tensorboard==2.20.0
    # Bioimage and CV
    - tifffile==2025.12.12
    - h5py==3.15.1
    - zarr==3.1.5
    - vigra==1.12.2
    - python-elf==0.7.3
    - python-graphviz==0.21
    - scikit-image==0.25.2
    - bioimageio.core==0.9.5
    - bioimageio.spec==0.5.6.0
    # GUI
    - qtpy==2.4.3
    - pyside6==6.10.1
    - napari==0.6.6
    - qt-material==2.14
    # Other
    - requests==2.32.5
    - pyyaml==6.0.3
    - pydantic==2.11.10

test:
  imports:
    - panseg
  requires:
    - python {{ python_min }}
    - pytest
    - pytest-qt
    - pytest-mock
    - requests-mock
  run:
    - pytest

about:
  home: https://kreshuklab.github.io/panseg/
  license: MIT
