package:
  name: plantseg
  version: "2.0.0b7"

source:
  path: ..

build:
  noarch: python
  number: 1
  script:
    - "pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
    - "mkdir -p {{ PREFIX }}/Menu" # [not win]
    - "cp {{ RECIPE_DIR }}/../Menu/plant-seg.json {{ PREFIX }}/Menu/{{ PKG_NAME }}_menu.json" # [not win]
    - "cp {{ RECIPE_DIR }}/../Menu/icon.png {{ PREFIX }}/Menu/icon.png" # [not win]
    - "cp {{ RECIPE_DIR }}/../Menu/logo_horizontal.png {{ PREFIX }}/Menu/logo_horizontal.png" # [not win]
    - "cp {{ RECIPE_DIR }}/../Menu/logo_vertical.png {{ PREFIX }}/Menu/logo_vertical.png" # [not win]
    - 'mkdir -p {{ PREFIX }}\Menu' # [win]
    - 'cp {{ RECIPE_DIR }}\..\Menu/plant-seg.json {{ PREFIX }}\Menu\{{ PKG_NAME }}_menu.json' # [win]
    - 'cp {{ RECIPE_DIR }}\..\Menu\icon.png {{ PREFIX }}\Menu\icon.png' # [win]
    - 'cp {{ RECIPE_DIR }}\..\Menu\logo_horizontal.png {{ PREFIX }}\Menu\logo_horizontal.png' # [win]
    - 'cp {{ RECIPE_DIR }}\..\Menu\logo_vertical.png {{ PREFIX }}\Menu\logo_vertical.png' # [win]

  entry_points:
    - plantseg = plantseg.run_plantseg:main

requirements:
  build:
    - python>=3.11
    - setuptools

  run:
    - python>=3.11
    - pip
    - pytorch
    - tifffile
    - h5py
    - zarr
    - vigra
    - python-elf
    - python-graphviz
    - scikit-image
    - bioimageio.core>=0.9.0
    - bioimageio.spec>=0.5.4.3
    - qtpy
    - pyqt
    - napari
    - qt-material
    - requests
    - pyyaml
    - pydantic>2

test:
  imports:
    - plantseg
  requires:
    - pytest
  run:
    - pytest

about:
  home: https://kreshuklab.github.io/plant-seg/
  license: MIT
