package:
  name: plantseg
  version: "2.0.0b3"

source:
  path: ..

build:
  noarch: python
  number: 1
  script:
    - "pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
    - "mkdir -p {{ PREFIX }}/Menu"
    - "cp {{ RECIPE_DIR }}/../Menu/plant-seg.json {{ PREFIX }}/Menu/{{ PKG_NAME }}_menu.json"
    - "cp {{ RECIPE_DIR }}/../Menu/logo.png {{ PREFIX }}/Menu/logo.png"

  entry_points:
    - plantseg = plantseg.run_plantseg:main

requirements:
  build:
    - python
    - pip
    - setuptools

  run:
    - python>=3.11
    - pip
    - pytorch-gpu
    - tifffile
    - h5py
    - zarr
    - vigra
    - python-elf
    - python-graphviz
    - scikit-image
    - bioimageio.core >=0.6.5,<=0.7.0
    - xarray<2025.3.0 # 2025.3.0 cause problem plant-seg/issues/396
    - qtpy
    - pyqt
    - napari
    - requests
    - pyyaml
    - pydantic >2,<2.10 # 2.10 cause problem spec-bioimage-io/issues/663
    - xarray <2025.3.0

test:
  imports:
    - plantseg
  requires:
    - pytest
  run:
    - pytest

about:
  home: https://kreshuklab.github.io/plant-seg/
  license: MIT
