package:
  name: plantseg
  version: {{ RELEASE_VERSION }}  # Do not change this line, not even adding space

source:
  path: ..

build:
  noarch: python
  script: "pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  number: 1

  entry_points:
    - plantseg = plantseg.run_plantseg:main

requirements:
  build:
    - python
    - pip
    - setuptools

  run:
    - python >=3.9
    - pytorch >=1.7.0
    - tifffile
    - h5py
    - zarr
    - vigra
    - python-elf
    - python-graphviz
    - scikit-image
    - bioimageio.core >=0.6.5,<=0.7.0
    - xarray<2025.3.0  # 2025.3.0 cause problem plant-seg/issues/396
    - napari
    - pyqt
    - requests
    - pyyaml
    - pydantic >2,<2.10  # 2.10 cause problem spec-bioimage-io/issues/663

test:
  imports:
    - plantseg
  requires:
    - pytest
  run:
    - pytest

about:
  home: https://kreshuklab.github.io/plant-seg/
  license: MIT
