name: Docs Build and Publish
on: workflow_dispatch

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ":99.0"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4

      # Start X virtual framebuffer for GUI testing
      - name: Start Xvfb
        run: |
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid \
          --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX

      - name: Set Up Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.11
          miniforge-version: latest
          mamba-version: "*"
          channels: conda-forge
          environment-file: "environment-dev.yaml"
          activate-environment: "plant-seg-dev"
          conda-remove-defaults: true

      - name: Build Docks
        run: |
          conda activate plant-seg-dev
          pytest -s --cov --cov-report=xml
          conda deactivate

      # Install MkDocs and deploy the documentation to GitHub Pages
      - name: Install MkDocs and Deploy
        shell: bash -l {0}
        run: |
          conda activate plant-seg
          pip install mkdocs-material \
                      mkdocs-git-revision-date-localized-plugin \
                      mkdocs-git-committers-plugin-2 \
                      mkdocs-autorefs \
                      mkdocstrings[python] \
                      markdown-exec
          mkdocs gh-deploy --force
        env:
          MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.MKDOCS_GIT_COMMITTERS_APIKEY }}
