name: Docs Build and Publish
on: workflow_dispatch

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        # Conda requires a login shell in order to work properly
        shell: bash -l {0}
    env:
      DISPLAY: ":99.0"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Qt
        uses: tlambert03/setup-qt-libs@v1

      # Start X virtual framebuffer for GUI testing
      - name: Start Xvfb
        run: |
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid \
          --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX

      - name: Set Up Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.11
          miniforge-version: latest
          mamba-version: "*"
          channels: conda-forge
          environment-file: "environment-dev.yaml"
          activate-environment: "plant-seg-dev"
          conda-remove-defaults: true

      # Install MkDocs and deploy the documentation to GitHub Pages
      - name: Install MkDocs and Deploy
        shell: bash -l {0}
        run: |
          conda activate plant-seg-dev
          pip install mkdocs-material \
                      mkdocs-git-revision-date-localized-plugin \
                      mkdocs-git-committers-plugin-2 \
                      mkdocs-autorefs \
                      mkdocstrings[python] \
                      markdown-exec
          mkdocs gh-deploy --force
        env:
          MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.MKDOCS_GIT_COMMITTERS_APIKEY }}
