name: "PR Title: Conventional Commit Lint"

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  lint_pr_title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install commitlint and the conventional config
      - name: Install Commitlint
        run: |
          npm install --no-save @commitlint/{cli,config-conventional}

      # Lint the PR title against Conventional Commits
      - name: Lint PR title
        run: |
          # dump the PR title into a file
          echo "${{ github.event.pull_request.title }}" > pr_title.txt
          # lint that file
          npx commitlint \
            --config node_modules/@commitlint/config-conventional \
            --edit pr_title.txt
