name: "PR Title: Conventional Commit Lint"

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  lint_pr_title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install commitlint and the conventional config
      - name: Install Commitlint
        run: |
          npm install --no-save @commitlint/{cli,config-conventional}

      # Lint the PR title against Conventional Commits
      - name: Lint PR title
        run: |
          echo "${{ github.event.pull_request.title }}" \
          | npx commitlint --config @commitlint/config-conventional
